### ISSUE TITLE
Ability to ignore set of notebooks from test suite

### ISSUE THREAD

**Issue by amit1rrr** [ReviewNB/treon#1]
Usually we have some _rough_ notebooks and some final notebooks in the same repo. We never want to run tests for _rough_ notebooks. It would be great to have `.ci_ignore` file that can be used to specify list of notebooks/directories that should be excluded from test suite.

Current workaround is to actually specify path of the notebooks/directories that needs to be included in the test suite.

**Comment by NiNXHeart** [comment]
Enhancement Will functon better

**Comment by amit1rrr** [comment]
Thanks to the [contribution](https://github.com/ReviewNB/treon/pull/16) from @midokura-silvia we now have ability to exclude notebooks & directories from testing.
