### ISSUE TITLE
Could you add support for linting/formatting?

### ISSUE THREAD

**Issue by sebinsua** [ReviewNB/treon#3]
I think it would be nice to autoformat the code written in notebooks using `black` and possibly lint with `pycodestyle`, etc.

Could support for this be added?

**Comment by amit1rrr** [comment]
While lint'ing & auto-formatting is important, I'm hesitant to include it in treon. I strongly believe in (the unix philosophy) of do one thing and do it well. Without that tools become bloated over time and hard to use.

I can imagine it to be a separate tool for notebook lint'ing with support for pylint/black etc.
