### ISSUE TITLE
Merge projects?

### ISSUE THREAD

**Issue by timkpaine** [ReviewNB/treon#5]
Any interest in merging projects? 
https://github.com/timkpaine/jupyterlab_celltests

**Comment by amit1rrr** [comment]
I looked at jupyterlab_celltests briefly and couldn't figure out exactly what it does from the Readme. From what I understand, it's a Jupyter lab plugin that let's you write tests for each cell and stores them as cell metadata. There's probably some mocking support as well. Can you please explain the tool briefly? (how does one install it, what type of tests user can write etc). 

Also, if you have a general idea on what functionalities would be useful to merge that would be great.

**Comment by timkpaine** [comment]
Yep, so basically there's a UI component for JupyterLab which lets you write tests for individual cells:
<img width="956" alt="Screen Shot 2019-05-13 at 9 09 14 AM" src="https://user-images.githubusercontent.com/3105306/57624035-0c498b00-755f-11e9-852a-2c0aa9988da5.png">

You can also configure some top-level assertions like >50% of cells have tests, there are no more than 10 lines in a given cell, etc, all of which are designed to further enforce the notion of notebooks as simple, slim, linearly-executed structures. 
<img width="547" alt="Screen Shot 2019-05-13 at 9 09 44 AM" src="https://user-images.githubusercontent.com/3105306/57624067-21beb500-755f-11e9-84ef-19cfc19bb336.png">


The on the backend, there are really 2 commands, `lint` and `test`. 
<img width="508" alt="Screen Shot 2019-05-13 at 9 10 01 AM" src="https://user-images.githubusercontent.com/3105306/57624116-4450ce00-755f-11e9-88ff-a654dc6be831.png">

`Lint` will basically check your top-level assertions (could be extended to include linting the python code using a linter, but notebook code is usually too different to get relevant results).
<img width="692" alt="Screen Shot 2019-05-13 at 9 10 07 AM" src="https://user-images.githubusercontent.com/3105306/57624167-61859c80-755f-11e9-8883-e1a18a497181.png">


And `test` basically extracts your notebook python and cell tests into a standard python unittest and runs your cell tests and top level assertions with pytest.
<img width="952" alt="Screen Shot 2019-05-13 at 9 10 25 AM" src="https://user-images.githubusercontent.com/3105306/57624226-81b55b80-755f-11e9-8eb2-0849a4445d02.png">

Both `lint` and `test` results are usable from python and exposed in the jupyterlab UI.

**Comment by amit1rrr** [comment]
Thanks for explaining. Looks like a pretty useful tool. I would updated the Readme to convey this and how to get started. 

About merging projects - these are both primarily in different formats for users to consume. 
 (JupyterLab UI vs cmdline). I don't see a path to really merge these as such and offering them both in a single tool is not ideal since we'll just be bloated with lot of options. I definitely want to support pytests in treon so maybe I will reach out to you for that. Here's the issue for it: https://github.com/ReviewNB/treon/issues/2
