### ISSUE TITLE
Linter + CI

### ISSUE THREAD

**Issue by f4lco** [ReviewNB/treon#7]
During development for #4, I felt like the following essentials might be missing from treon:

- [x] `.gitignore` - for `__pycache__`
- [x] ~~`Pipfile` and `Pipfile.lock` - easier to get started, because there are already non-standard dependencies like docopt.~~
- [x] Document dependency set-up (see "Note about dependencies" in readme)
- [x] [Pylint](https://www.pylint.org/) - code is in good shape, better keep it that way
- [x] basic sanity tests
- [x] [Travis](https://travis-ci.com/)? - to exercise above effectively

How do you feel about this list, @amit1rrr ?

**Comment by amit1rrr** [comment]
Definitely a good list. Just added [standard .gitignore for Python] with some additions for vscode etc. (https://github.com/github/gitignore/blob/master/Python.gitignore) 

About Pipfile - For development, isn't it better to just install packages from setup.py (with `pip install -e .`) ? 

Pylint - Sure. I hate some of their rules but it's better to have a common, enforceable standard. Plus we can always turn off annoying rules ;)

Travis - Yes. I think we should have some basic sanity tests in there (arguably before any of the above).  Once there, travis would be super useful. For someone who might take a stab at this before me, Here's a reference for another package I setup with travis -https://github.com/amit1rrr/numcompress/blob/master/.travis.yml

**Comment by f4lco** [comment]
> About Pipfile - Isn't it better to just install packages from setup.py (with pip install -e .) for development?

Well, "better" depends. [This article](https://packaging.python.org/discussions/install-requires-vs-requirements/) explains a bit. The main difference that with `Pipfile` and `Pipfile.lock` targets repeatable installations, in which every dependency is pinned, whereas dependencies in `setup.py` are deliberately fuzzy ("abstract").
I was going to blindly advocate Pipenv, but now realized this project maybe does not need pinned dependencies at all, with such a minimal, stable set of dependencies. I want to derive the following tasks:
* document `pip install -e .` in readme (I was simply unaware of that)
* Maybe add a "requirements-dev.txt" at a later stage, when test dependencies creep in, or for linting, or else.

**Comment by amit1rrr** [comment]
> document pip install -e . in readme (I was simply unaware of that)
 
> Maybe add a "requirements-dev.txt" at a later stage, when test dependencies creep in, or for linting, or else.

Sounds good!

**Comment by f4lco** [comment]
Appears all todos from above list are done 🙂
